version: '3'
services:
  backend:
    image: sankeerthanak/airbnbreplica:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
